# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

 config.vm.define "alma_1" do |alma_1| 
 
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  alma_1.vm.box = "almalinux/10"
  alma_1.vm.box_version = "10.1.20260110"
  
  alma_1.vm.hostname = "alma-1"
  
  alma_1.vm.disk :disk, size: "50GB", primary: true

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "VirtualBox Host-Only Ethernet Adapter", type: "dhcp"
  
  # doesn't work # config.vm.network "private_network", type: "dhcp", name: "VirtualBox Host-Only Ethernet Adapter"
  
  # see commands at https://docs.oracle.com/en/virtualization/virtualbox/6.0/user/vboxmanage-modifyvm.html
  alma_1.vm.provider "virtualbox" do |vb|
     vb.customize ["modifyvm", :id, "--nic2", "hostonly"]
     vb.customize ["modifyvm", :id, "--hostonlyadapter2", "VirtualBox Host-Only Ethernet Adapter"] #use proper network name here
     vb.customize ["modifyvm", :id, "--cableconnected2", "on"]
  end

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Disable the default share of the current code directory. Doing this
  # provides improved isolation between the vagrant box and your host
  # by making sure your Vagrantfile isn't accessible to the vagrant box.
  # If you use this you may want to enable additional shared subfolders as
  # shown above.
  # config.vm.synced_folder ".", "/vagrant", disabled: true
  
  # alma_1.vm.synced_folder ".", "/vagrant", disabled: true

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  alma_1.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = true
  
     # Customize the amount of memory on the VM:
     vb.memory = "8192"
     vb.cpus = 2
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
  
  
  alma_1.vm.provision "shell", path: "provision.sh"
  
  # This shell provisioner will trigger a reboot
  alma_1.vm.provision "shell", reboot: true, inline: "echo 'Rebooting now...'"
  
  # This runs AFTER the reboot
  alma_1.vm.provision "shell", inline: "echo 'Machine is back up!'"
  
  
  end # alma_1
  
  # just the commands without the comments
  config.vm.define "alma_2" do |alma_2|
  
     alma_2.vm.box = "almalinux/10"
     alma_2.vm.box_version = "10.1.20260110"
     
     alma_2.vm.disk :disk, size: "50GB", primary: true
     
     # alma_2.vm.synced_folder ".", "/vagrant", disabled: true
     
     alma_2.vm.hostname = "alma-2"
  
     alma_2.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--nic2", "hostonly"]
        vb.customize ["modifyvm", :id, "--hostonlyadapter2", "VirtualBox Host-Only Ethernet Adapter"] #use proper network name here
        vb.customize ["modifyvm", :id, "--cableconnected2", "on"]
     end
  
     alma_2.vm.provider "virtualbox" do |vb|
        # Display the VirtualBox GUI when booting the machine
        vb.gui = true
  
        # Customize the amount of memory on the VM:
        vb.memory = "1024"
        vb.cpus = 2
     end
  
     # this shell provisioner will run the provisioning file
     alma_2.vm.provision "shell", path: "provision.sh"
     
     # This shell provisioner will trigger a reboot
     alma_2.vm.provision "shell", reboot: true, inline: "echo 'Rebooting now...'"
  
     # This runs AFTER the reboot
     alma_2.vm.provision "shell", inline: "echo 'Machine is back up!'"
   
  end  # alma_2
  
  
  
end
