Vagrant.configure("2") do |config|
  config.vm.define :pxe_client do |pxe_client|

    # We need a box to start with, but we will not use it for anything other than bootstrapping the VM. 
    # we are using rockylinux-9.6 as the base box, but it will be replaced by the PXE boot process with ubuntu.
    # The PXE boot process will take over from there.
    pxe_client.vm.box = 'bento/rockylinux-9.6'

#    pxe_client.vm.provider :libvirt do |libvirt|
#      libvirt.cpu_mode = 'host-passthrough'
#      libvirt.memory = '1024'
#      libvirt.cpus = '1'
#      libvirt.storage :file, :size => '10G', :type => 'qcow2'
#      libvirt.boot 'network'
#      libvirt.mgmt_attach = 'false'
#      libvirt.management_network_name = "pxe_network"
#      libvirt.management_network_address = "192.168.0.0/24"
#      libvirt.management_network_mode = "nat"
#    end

    pxe_client.vm.provider :virtualbox do |vb|
      vb.memory = '10240'
      vb.cpus = '1'
      vb.gui = 'true'
      
      # Change the display driver to VMSVGA, VBoxSVGA, VBoxVGA, or none
      vb.customize ["modifyvm", :id, "--graphicscontroller", "VBoxSVGA"]
         
         # Optional: You can also increase the Video RAM (VRAM) in MB if needed
      vb.customize ["modifyvm", :id, "--vram", "128"]

      vb.customize [
        'modifyvm', :id,
        '--nic1', 'intnet',
        '--intnet1', 'pxe_network',
        '--boot1', 'net',
        '--boot2', 'none',
        '--boot3', 'none',
        '--boot4', 'none'
      ]

    end
  end
end
